
GET http://localhost:3000/movies/10


###

GET http://localhost:3000/movies


###
POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "greatings", 
  "year": 2007, 
  "plot": "Boy Marries Girl"
}
###

PATCH http://localhost:3000/movies/11
Content-Type: application/json

{
  "title": "tmilite", 
  "year": 2010, 
  "plot": "Boy Marries Girl"
}

###
DELETE http://localhost:3000/movies/10





